### ISSUE TITLE
UI Upgrade Request

### ISSUE THREAD

**Issue by stp14-z** [MineCronik/MaxxOS#1]
Hi Mkn,
Your Maxx OS v0.2 developed by Scratch was amazing, and I am looking forward to your new version based on Linux as well. However, your resolution setting was unexpected to me, and I do think that's a really big faulty problem because most of our computers now is 1920 x 1080 (16:9) or even higher in the same proportion, and your MaxxOS version 0.2 was in an unknown resolution and it will get black lines beside the main page. As a operating system, you need to fit with customers' demand.
After all, I would love to see your changes from Scratch to Linux, which is really a change in the quality.

(Ps: reply with Chinese is supported.)

Yours Sincerely
Xiaoran Zhou [Shawn]
16/06/2020

**Comment by MineCronik** [comment]
Hello, thank you for your report.
Because of Sscratch has few functions and low resolution, we will make it based on Linux system in the later version, which will fix many problems.

**Comment by stp14-z** [comment]
> Hello, thank you for your report.
> Because of Sscratch has few functions and low resolution, we will make it based on Linux system in the later version, which will fix many problems.

Thanks, I am really looking forward to the new version of Maxx OS, hope you could build a better version which can be comparable with os such as UOS and Windows.

(Ps: Scratch is spelt "S-C-R-A-T-C-H" ![Annotation 2020-06-16 203914](https://user-images.githubusercontent.com/59436839/84764675-74478c00-b011-11ea-9d76-66cf9bcc8df7.jpg))

Yours Sincerely
Xiaoran ZHOU [Shawn]
16/06/2020
