### ISSUE TITLE
Login System Upgrade Request

### ISSUE THREAD

**Issue by stp14-z** [MineCronik/MaxxOS#2]
Hi Mkn again,
I would like you to upgrade your login system. Your account registration function was already developed really well just with some ui problems but I think you will fix that shortly, however your log in function wasn't really good after a while of experiment, the main problem is that when you close the program and reopen it, you can only re-register a new account instead of logging into your old one. That caused us to open lots of accounts instead having one belongs to our own.
So on, create an account with simply a account name is not really enough, you could try add things such as "link your mobile number" or "add your email address" for safety reasons.
Try to upgrade your log in UI to the level **Paypal** and other big company websites did, and try to make one account apply to all your products such as login to your website and apps.

Yours Sincerely
Xiaoran ZHOU [Shawn]
16/06/2020

**Comment by MineCronik** [comment]
Hello, thank you for your report.
Because of scratch has few functions, we really can't figure out how to make a better login interface(Like user storage etc.) But anyway, our Linux version will fix the login interface.
